Update lists.ts
lootproject/website pull request #83
Opened 2021-09-09 11:38 UTC by sexyLoot

<!-- 
Please use this pull request template when adding a new resource to the website. 
You do not have to fill out all the fields, but please attempt to complete as many as possible.

sexyLoot sLoots

Etherscan link: https://etherscan.io/address/0xb13EFaB167751A95EC6F9844944C74Aa668ddeD6#writeContract

Website: https://sexyloot.co/

Twitter: https://twitter.com/LootSexy

2021-09-09 14:40 UTC, sexyLoot commented
Followed the instructions from here
https://github.com/lootproject/website/pull/70
But now not sure what "checks have failed" means?

2021-09-09 14:54 UTC, ravindranrahul requested changes

2021-09-09 14:54 UTC, ravindranrahul commented on utils/lists.ts
> +    name: “sexy Loot - sLoots“,
Please remove the double quotes and type them manually or copy what you done with the url

2021-09-09 14:54 UTC, ravindranrahul commented on utils/lists.ts
> +    description: “sLoots are on-chain harlots and strumpets.”,
Update the quotes here as well.

2021-09-10 00:25 UTC, sexyLoot commented on utils/lists.ts
> +    description: “sLoots are on-chain harlots and strumpets.”,
Ah darn it. Got it.

2021-09-10 00:31 UTC, closed without merging